Repository onflow/flow-js-testing, pull requests merged in 2022-08, with the labels that each got.

#158 Fix custom signers
  .changeset/afraid-planets-beam.md
  .changeset/clean-oranges-hammer.md
  .changeset/kind-fishes-switch.md
  .changeset/pre.json
  .changeset/tasty-fans-repeat.md
  CHANGELOG.md
  cadence/transactions/create-account.cdc
  dev-test/account.test.js
  dev-test/interaction.test.js
  dev-test/util/permute.js
  dev-test/util/validate-key-pair.js
  dev-test/utilities.test.js
  docs/accounts.md
  docs/api.md
  docs/emulator.md
  docs/send-transactions.md
  examples/01-get-account-address.test.js
  examples/04-get-contract-address.test.js
  examples/09-send-transaction.test.js
  package-lock.json
  package.json
  src/account.js
  src/crypto.js
  src/generated/transactions/createAccount.js
  src/index.js
  src/utils.js
Labels: bug

#167 Remove redundant flow-cadut functions and export from there instead
  src/imports.js
Labels: enhancement

#169 Fix relative links for docs site
  docs/api.md
  docs/contracts.md
  docs/execute-scripts.md
  docs/index.md
  docs/jest-helpers.md
  docs/send-transactions.md
Labels: bug

#165 Make block/timestamp offset utilities work in contracts & deprecate builtInMethods transformer
  .changeset/red-vans-explode.md
  TRANSITIONS.md
  dev-test/utilities.test.js
  docs/api.md
  docs/contracts.md
  docs/emulator.md
  docs/execute-scripts.md
  docs/send-transactions.md
  src/deploy-code.js
  src/emulator.js
  src/index.js
  src/interaction.js
  src/manager.js
  src/transformers.js
Labels: bug, enhancement

#173 Sisyphus smiling/set jest config timeout
  docs/install.md
  src/cli/templates/jest-config.js
Labels: good first issue

#166 Add signUserMessage & verifyUserSignatures utilites
  .changeset/quick-carrots-type.md
  dev-test/crypto.test.js
  dev-test/util/validate-key-pair.js
  docs/api.md
  src/crypto.js
  src/deploy-code.js
  src/index.js
  src/interaction.js
  src/manager.js
  src/utils.js
Labels: enhancement
